const teamLogos = {
    "ATA": "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
    "BOL": "https://a.espncdn.com/i/teamlogos/soccer/500/203.png",
    "CAG": "https://a.espncdn.com/i/teamlogos/soccer/500/2808.png",
    "COM": "https://a.espncdn.com/i/teamlogos/soccer/500/2822.png",
    "FIO": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
    "FRO": "https://a.espncdn.com/i/teamlogos/soccer/500/12316.png",
    "GEN": "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
    "INT": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
    "JUV": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
    "LAZ": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
    "LEC": "https://a.espncdn.com/i/teamlogos/soccer/500/3444.png",
    "MIL": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
    "MON": "https://a.espncdn.com/i/teamlogos/soccer/500/18840.png",
    "NAP": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
    "PAR": "https://a.espncdn.com/i/teamlogos/soccer/500/115.png",
    "ROM": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
    "SAS": "https://a.espncdn.com/i/teamlogos/soccer/500/11698.png",
    "TOR": "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
    "UDI": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
    "VEN": "https://a.espncdn.com/i/teamlogos/soccer/500/3264.png"
};
