const teamLogos = {
    "ATA": "loghi/ata.png",
    "BOL": "loghi/bol.png",
    "CAG": "loghi/cag.png",
    "COM": "loghi/com.png",
    "FIO": "loghi/fio.png",
    "FRO": "loghi/fro.png",
    "GEN": "loghi/gen.png",
    "INT": "loghi/int.png",
    "JUV": "loghi/juv.png",
    "LAZ": "loghi/laz.png",
    "LEC": "loghi/lec.png",
    "MIL": "loghi/mil.png",
    "MON": "loghi/mon.png",
    "NAP": "loghi/nap.png",
    "PAR": "loghi/par.png",
    "ROM": "loghi/rom.png",
    "SAS": "loghi/sas.png",
    "TOR": "loghi/tor.png",
    "UDI": "loghi/udi.png",
    "VEN": "loghi/ven.png"
};
